version: '3.9'

services:
  cht-upgrade-service:
    build: .
    container_name: cht-upgrade-service
    ports:
      - "5100:5100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_PATH}:/config
      - ${CHT_COMPOSE_PATH}:/docker-compose
    command: node /app/src/index.js
    networks:
      - cht-net
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
      - COUCH_PORT
      - API_PORT
      - MARKET_URL_READ
      - BUILDS_SERVER
      - DOCKER_CONFIG=/config

networks:
  cht-net:
    name: cht-net
