version: '3.9'

services:
  cht-upgrade-service:
    image: public.ecr.aws/s5s3h4s7/cht-upgrade-service:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_PATH}:/config
      - ${CHT_COMPOSE_PATH}:/docker-compose
    networks:
      - cht-net
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
      - COUCHDB_SECRET
      - COUCHDB_UUID
      - COUCHDB_DATA
      - API_PORT
      - MARKET_URL_READ
      - BUILDS_SERVER
      - CERTIFICATE_MODE
      - SSL_CERT_FILE_PATH
      - SSL_KEY_FILE_PATH
      - COMMON_NAME
      - EMAIL
      - COUNTRY
      - STATE
      - LOCALITY
      - ORGANISATION
      - DEPARTMENT
      - DOCKER_CONFIG=/config
      - CHT_COMPOSE_PROJECT_NAME=${CHT_COMPOSE_PROJECT_NAME:-cht}

networks:
  cht-net:
    name: ${CHT_NETWORK:-cht-net}
