version: '3.9'

services:
  cht-upgrade-service:
    image: ${ECR_REPO:-medicmobile}/cht-upgrade-service:latest
    container_name: cht-upgrade-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_PATH}:/config
      - ${CHT_COMPOSE_PATH}:/docker-compose
    networks:
      - cht-net
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
      - COUCHDB_SECRET
      - COUCHDB_UUID
      - API_PORT
      - MARKET_URL_READ
      - BUILDS_SERVER
      - DOCKER_CONFIG=/config

networks:
  cht-net:
    name: cht-net
